/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef COMPANION_DEVICE_AUTH_IAM_LOG_TRACER_H
#define COMPANION_DEVICE_AUTH_IAM_LOG_TRACER_H

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "nocopyable.h"

namespace OHOS {
namespace UserIam {
namespace CompanionDeviceAuth {

enum LogTraceFileId : uint16_t {
    LOG_FILE_UNKNOWN = 0,

    // services/external_adapters (0x010x)
    LOG_FILE_CONSTANT_USER_ID_MANAGER = 0x0100,
    LOG_FILE_DEFAULT_USER_ID_MANAGER = 0x0101,
    LOG_FILE_SYSTEM_PARAM_MANAGER_IMPL = 0x0102,
    LOG_FILE_EVENT_MANAGER_ADAPTER_IMPL = 0x0103,
    LOG_FILE_DRIVER_MANAGER_ADAPTER_IMPL = 0x0104,
    LOG_FILE_IDM_ADAPTER_IMPL = 0x0105,
    LOG_FILE_USER_AUTH_ADAPTER_IMPL = 0x0106,
    LOG_FILE_ADAPTER_MANAGER = 0x0107,
    LOG_FILE_XCOLLIE_HELPER = 0x0108,
    LOG_FILE_SA_MANAGER_ADAPTER_IMPL = 0x0109,
    LOG_FILE_SECURITY_COMMAND_ADAPTER_IMPL = 0x010A,
    LOG_FILE_CDA_FFI_UTIL = 0x010B,
    LOG_FILE_TIME_KEEPER_IMPL = 0x010C,
    LOG_FILE_CDA_FFI_ARRAY_UTIL = 0x010D,

    // services/host_binding (0x011x)
    LOG_FILE_HOST_BINDING_MANAGER_IMPL = 0x0110,
    LOG_FILE_HOST_BINDING = 0x0111,

    // services/misc (0x012x)
    LOG_FILE_MISC_MANAGER_IMPL = 0x0120,

    // services/singleton (0x013x)
    LOG_FILE_SINGLETON_MANAGER = 0x0130,

    // services/security_agent (0x014x)
    LOG_FILE_SECURITY_AGENT_IMPL = 0x0140,

    // services/cross_device_comm (0x015x)
    LOG_FILE_CHANNEL_MANAGER = 0x0150,
    LOG_FILE_CONNECTION_MANAGER = 0x0151,
    LOG_FILE_DEVICE_STATUS_MANAGER = 0x0152,
    LOG_FILE_MESSAGE_ROUTER = 0x0153,
    LOG_FILE_CROSS_DEVICE_COMM_MANAGER_IMPL = 0x0154,
    LOG_FILE_LOCAL_DEVICE_STATUS_MANAGER = 0x0155,
    LOG_FILE_DEVICE_STATUS_ENTRY = 0x0156,

    // services/cross_device_channels/soft_bus (0x016x)
    LOG_FILE_SOFT_BUS_CHANNEL = 0x0160,
    LOG_FILE_SOFT_BUS_DEVICE_STATUS_MANAGER = 0x0161,
    LOG_FILE_DM_ADAPTER_IMPL = 0x0162,
    LOG_FILE_SOFT_BUS_CONNECTION = 0x0163,
    LOG_FILE_SOFT_BUS_ADAPTER_MANAGER = 0x0164,
    LOG_FILE_SOFT_BUS_CONNECTION_MANAGER = 0x0165,
    LOG_FILE_SOFT_BUS_ADAPTER_IMPL = 0x0166,

    // services/utils (0x017x)
    LOG_FILE_SA_STATUS_LISTENER = 0x0170,
    LOG_FILE_TEMPORARY_TASK_RUNNER = 0x0171,
    LOG_FILE_ACCESS_TOKEN_KIT = 0x0172,
    LOG_FILE_RESIDENT_TASK_RUNNER = 0x0173,
    LOG_FILE_BACKOFF_RETRY_TIMER = 0x0174,
    LOG_FILE_CALLBACK_DEATH_RECIPIENT = 0x0175,
    LOG_FILE_TASK_RUNNER_MANAGER = 0x0176,
    LOG_FILE_RELATIVE_TIMER = 0x0177,
    LOG_FILE_SUBSCRIPTION = 0x0178,
    LOG_FILE_CDA_ATTRIBUTES = 0x0179,

    // services/fwk_comm (0x018x)
    LOG_FILE_PENDING_ISSUE_TOKEN_MANAGER = 0x0180,
    LOG_FILE_CDA_ALL_IN_ONE_EXECUTOR = 0x0181,
    LOG_FILE_DEFAULT_EXECUTOR_FACTORY = 0x0182,
    LOG_FILE_CDA_DRIVER = 0x0183,
    LOG_FILE_CDA_EXECUTOR_CALLBACK = 0x0184,
    LOG_FILE_FWK_COMM_MANAGER = 0x0185,

    // services/event_bus (0x019x)
    LOG_FILE_EVENT_BUS_IMPL = 0x0190,

    // services/cross_device_interaction (0x01Ax–0x01Cx)
    LOG_FILE_OBTAIN_TOKEN_MESSAGE = 0x01A0,
    LOG_FILE_HOST_OBTAIN_TOKEN_REQUEST = 0x01A1,
    LOG_FILE_COMPANION_OBTAIN_TOKEN_REQUEST = 0x01A2,
    LOG_FILE_HOST_PRE_OBTAIN_TOKEN_HANDLER = 0x01A3,
    LOG_FILE_COMPANION_REMOVE_HOST_BINDING_HANDLER = 0x01A4,
    LOG_FILE_HOST_REMOVE_HOST_BINDING_REQUEST = 0x01A5,
    LOG_FILE_REMOVE_HOST_BINDING_MESSAGE = 0x01A6,
    LOG_FILE_COMPANION_DELEGATE_AUTH_REQUEST = 0x01A7,
    LOG_FILE_DELEGATE_AUTH_MESSAGE = 0x01A8,
    LOG_FILE_COMPANION_START_DELEGATE_AUTH_HANDLER = 0x01A9,
    LOG_FILE_HOST_DELEGATE_AUTH_REQUEST = 0x01AA,
    LOG_FILE_TOKEN_AUTH_MESSAGE = 0x01AB,
    LOG_FILE_COMPANION_TOKEN_AUTH_HANDLER = 0x01AC,
    LOG_FILE_HOST_TOKEN_AUTH_REQUEST = 0x01AD,
    LOG_FILE_COMPANION_ISSUE_TOKEN_REQUEST = 0x01AE,
    LOG_FILE_COMPANION_PRE_ISSUE_TOKEN_HANDLER = 0x01AF,
    LOG_FILE_ISSUE_TOKEN_MESSAGE = 0x01B0,
    LOG_FILE_HOST_ISSUE_TOKEN_REQUEST = 0x01B1,
    LOG_FILE_INCOMING_MESSAGE_HANDLER_REGISTRY = 0x01B2,
    LOG_FILE_SYNC_INCOMING_MESSAGE_HANDLER = 0x01B3,
    LOG_FILE_ASYNC_INCOMING_MESSAGE_HANDLER = 0x01B4,
    LOG_FILE_HOST_SINGLE_MIX_AUTH_REQUEST = 0x01B5,
    LOG_FILE_HOST_MIX_AUTH_REQUEST = 0x01B6,
    LOG_FILE_REQUEST_ABORTED_MESSAGE = 0x01B7,
    LOG_FILE_HOST_SYNC_DEVICE_STATUS_REQUEST = 0x01B8,
    LOG_FILE_COMPANION_SYNC_DEVICE_STATUS_HANDLER = 0x01B9,
    LOG_FILE_SYNC_DEVICE_STATUS_MESSAGE = 0x01BA,
    LOG_FILE_ADD_COMPANION_MESSAGE = 0x01BB,
    LOG_FILE_COMPANION_ADD_COMPANION_REQUEST = 0x01BC,
    LOG_FILE_COMPANION_INIT_KEY_NEGOTIATION_HANDLER = 0x01BD,
    LOG_FILE_HOST_ADD_COMPANION_REQUEST = 0x01BE,
    LOG_FILE_INBOUND_REQUEST = 0x01BF,
    LOG_FILE_BASE_REQUEST = 0x01C0,
    LOG_FILE_COMMON_MESSAGE = 0x01C1,
    LOG_FILE_OUTBOUND_REQUEST = 0x01C2,
    LOG_FILE_REVOKE_TOKEN_MESSAGE = 0x01C3,
    LOG_FILE_COMPANION_REVOKE_TOKEN_REQUEST = 0x01C4,
    LOG_FILE_HOST_REVOKE_TOKEN_HANDLER = 0x01C5,
    LOG_FILE_KEEP_ALIVE_HANDLER = 0x01C6,
    LOG_FILE_INTERACTION_EVENT_COLLECTOR = 0x01C7,

    // services/request (0x01Dx)
    LOG_FILE_REQUEST_MANAGER_IMPL = 0x01D0,
    LOG_FILE_REQUEST_FACTORY_IMPL = 0x01D1,

    // services/service_entry (0x01Ex)
    LOG_FILE_BASE_SERVICE_CORE = 0x01E0,
    LOG_FILE_CDA_SERVICE = 0x01E1,
    LOG_FILE_BASE_SERVICE_INITIALIZER = 0x01E2,
    LOG_FILE_SUBSCRIPTION_MANAGER = 0x01E3,
    LOG_FILE_SUBSCRIPTION_UTIL = 0x01E4,
    LOG_FILE_AVAILABLE_DEVICE_SUBSCRIPTION = 0x01E5,
    LOG_FILE_TEMPLATE_STATUS_SUBSCRIPTION = 0x01E6,
    LOG_FILE_CONTINUOUS_AUTH_SUBSCRIPTION = 0x01E7,
    LOG_FILE_CALLBACK_SUBSCRIPTION_BASE = 0x01E8,

    // services/companion (0x01Fx)
    LOG_FILE_COMPANION = 0x01F0,
    LOG_FILE_COMPANION_MANAGER_IMPL = 0x01F1,

    // common (0x030x)
    LOG_FILE_IAM_PARA2STR = 0x0300,

    // frameworks/ets/ani (0x031x)
    LOG_FILE_ANI_CONSTRUCTOR = 0x0310,
    LOG_FILE_CDA_ANI_HELPER = 0x0311,
    LOG_FILE_CDA_ANI_IMPL = 0x0312,
    LOG_FILE_ANI_AVAILABLE_DEVICE_STATUS_CB_WRAPPER = 0x0313,
    LOG_FILE_ANI_CONTINUOUS_AUTH_STATUS_CB_WRAPPER = 0x0314,
    LOG_FILE_ANI_DEVICE_SELECT_CALLBACK = 0x0315,
    LOG_FILE_ANI_PASSCODE_PROMPT_CALLBACK = 0x0316,
    LOG_FILE_ANI_TEMPLATE_STATUS_CB_WRAPPER = 0x0317,

    // frameworks/js/napi (0x032x)
    LOG_FILE_CDA_NAPI_ENTRY = 0x0320,
    LOG_FILE_CDA_NAPI_HELPER = 0x0321,
    LOG_FILE_NAPI_AVAILABLE_DEVICE_STATUS_CB_WRAPPER = 0x0322,
    LOG_FILE_NAPI_CONTINUOUS_AUTH_STATUS_CB_WRAPPER = 0x0323,
    LOG_FILE_NAPI_DEVICE_SELECT_CALLBACK = 0x0324,
    LOG_FILE_NAPI_PASSCODE_PROMPT_CALLBACK = 0x0325,
    LOG_FILE_NAPI_TEMPLATE_STATUS_CB_WRAPPER = 0x0326,

    // frameworks/native/client (0x033x)
    LOG_FILE_CDA_CLIENT_IMPL = 0x0330,
    LOG_FILE_ASYM_ENCRYPTOR = 0x0331,
    LOG_FILE_RSA_OAEP_ENCRYPTOR = 0x0332,
    LOG_FILE_SYSTEM_ABILITY_LISTENER = 0x0333,
    LOG_FILE_PASSCODE_SUBMIT_CALLBACK_IMPL = 0x0334,
    LOG_FILE_SET_DEVICE_SELECT_RESULT_CALLBACK = 0x0335,
    LOG_FILE_IPC_CLIENT_FETCHER = 0x0336,
    LOG_FILE_IPC_AVAILABLE_DEVICE_STATUS_CB_SERVICE = 0x0337,
    LOG_FILE_IPC_CONTINUOUS_AUTH_STATUS_CB_SERVICE = 0x0338,
    LOG_FILE_IPC_DEVICE_SELECT_CALLBACK_SERVICE = 0x0339,
    LOG_FILE_IPC_PASSCODE_PROMPT_CALLBACK_SERVICE = 0x033A,
    LOG_FILE_IPC_TEMPLATE_STATUS_CB_SERVICE = 0x033B,
};

struct LogEntry {
    int32_t code = 0;
    uint16_t fileId = 0;
    uint16_t lineNum = 0;
};

constexpr uint32_t MAX_LOG_TRACE_COUNT = 100;

class LogTracer : private NoCopyable {
public:
    static LogTracer &GetInstance()
    {
        thread_local LogTracer instance;
        return instance;
    }

    bool IsActive() const;
    void Record(uint16_t fileId, uint16_t lineNum, int32_t code = 0);
    void Import(const std::vector<LogEntry> &entries);
    std::string ExportAsString() const;

private:
    LogTracer() = default;
    ~LogTracer() = default;

    void WriteEntry(const LogEntry &entry);
    std::vector<LogEntry> Export() const;

    uint32_t activeGuardCount_ = 0;
    std::unique_ptr<std::array<LogEntry, MAX_LOG_TRACE_COUNT>> entries_;
    uint32_t recordCount_ = 0;
    uint32_t writeIndex_ = 0;

    friend class LogTraceGuard;
};

class LogTraceGuard : public NoCopyable {
public:
    LogTraceGuard();
    ~LogTraceGuard();
};

} // namespace CompanionDeviceAuth
} // namespace UserIam
} // namespace OHOS

#endif // COMPANION_DEVICE_AUTH_IAM_LOG_TRACER_H
