/*
 * Copyright (C) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Auto-generated C bindings for user_auth_rs
 * Generated by cbindgen from Rust FFI definitions
 */

#ifndef COMPANION_DEVICE_AUTH_FFI_H
#define COMPANION_DEVICE_AUTH_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

#define SALT_LEN_FFI 32

#define UDID_LEN_FFI 64

#define MAX_EVENT_NUM_FFI 20

#define MAX_TEMPLATE_ID_NUM_PER_USER_FFI 10

#define MAX_USER_NUM_FFI 5

#define MAX_DATA_LEN_64 64

#define MAX_DATA_LEN_128 128

#define MAX_DATA_LEN_256 256

#define MAX_DATA_LEN_1024 1024

#define MAX_STRUCT_SIZE_FFI 409600

#define AUTH_TOKEN_SIZE_FFI 256

enum CommandId {
    INIT = 1,
    GET_EXECUTOR_INFO = 2,
    HOST_REGISTER_FINISH = 1001,
    HOST_GET_PERSISTED_STATUS = 1002,
    HOST_BEGIN_COMPANION_CHECK = 1003,
    HOST_END_COMPANION_CHECK = 1004,
    HOST_CANCEL_COMPANION_CHECK = 1005,
    HOST_GET_INIT_KEY_NEGOTIATION = 1006,
    HOST_BEGIN_ADD_COMPANION = 1007,
    HOST_END_ADD_COMPANION = 1008,
    HOST_CANCEL_ADD_COMPANION = 1009,
    HOST_REMOVE_COMPANION = 1010,
    HOST_PRE_ISSUE_TOKEN = 1011,
    HOST_BEGIN_ISSUE_TOKEN = 1012,
    HOST_END_ISSUE_TOKEN = 1013,
    HOST_CANCEL_ISSUE_TOKEN = 1014,
    HOST_BEGIN_TOKEN_AUTH = 1015,
    HOST_END_TOKEN_AUTH = 1016,
    HOST_REVOKE_TOKEN = 1017,
    HOST_UPDATE_COMPANION_STATUS = 1018,
    HOST_UPDATE_COMPANION_ENABLED_BUSINESS_IDS = 1019,
    HOST_BEGIN_DELEGATE_AUTH = 1020,
    HOST_END_DELEGATE_AUTH = 1021,
    HOST_CANCEL_DELEGATE_AUTH = 1022,
    HOST_PROCESS_PRE_OBTAIN_TOKEN = 1023,
    HOST_PROCESS_OBTAIN_TOKEN = 1024,
    HOST_CANCEL_OBTAIN_TOKEN = 1025,
    HOST_ACTIVATE_TOKEN = 1026,
    HOST_CHECK_TEMPLATE_ENROLLED = 1027,

    COMPANION_GET_PERSISTED_STATUS = 2000,
    COMPANION_PROCESS_CHECK = 2001,
    COMPANION_INIT_KEY_NEGOTIATION = 2002,
    COMPANION_BEGIN_ADD_HOST_BINDING = 2003,
    COMPANION_END_ADD_HOST_BINDING = 2004,
    COMPANION_REMOVE_HOST_BINDING = 2005,
    COMPANION_PRE_ISSUE_TOKEN = 2006,
    COMPANION_PROCESS_ISSUE_TOKEN = 2007,
    COMPANION_CANCEL_ISSUE_TOKEN = 2008,
    COMPANION_PROCESS_TOKEN_AUTH = 2009,
    COMPANION_REVOKE_TOKEN = 2010,
    COMPANION_BEGIN_DELEGATE_AUTH = 2011,
    COMPANION_END_DELEGATE_AUTH = 2012,
    COMPANION_BEGIN_OBTAIN_TOKEN = 2013,
    COMPANION_END_OBTAIN_TOKEN = 2014,
    COMPANION_CANCEL_OBTAIN_TOKEN = 2015,
};

typedef struct RustCommandParam {
    int32_t commandId;
    const uint8_t *inputData;
    uint32_t inputDataLen;
    uint8_t *outputData;
    uint32_t outputDataLen;
    uint8_t *commonOutputData;
    uint32_t commonOutputDataLen;
} RustCommandParam;

typedef struct DataArray64Ffi {
    uint8_t data[MAX_DATA_LEN_64];
    uint32_t len;
} DataArray64Ffi;

typedef struct DataArray128Ffi {
    uint8_t data[MAX_DATA_LEN_128];
    uint32_t len;
} DataArray128Ffi;

typedef struct DataArray256Ffi {
    uint8_t data[MAX_DATA_LEN_256];
    uint32_t len;
} DataArray256Ffi;

typedef struct DataArray1024Ffi {
    uint8_t data[MAX_DATA_LEN_1024];
    uint32_t len;
} DataArray1024Ffi;

typedef struct TemplateIdArrayFfi {
    uint64_t data[MAX_TEMPLATE_ID_NUM_PER_USER_FFI];
    uint32_t len;
} TemplateIdArrayFfi;

typedef struct PlaceHolderFfi {
    uint8_t placeHolder;
} PlaceHolderFfi;

typedef struct EventFfi {
    uint64_t time;
    struct DataArray64Ffi fileName;
    uint32_t lineNumber;
    int32_t eventType;
    struct DataArray256Ffi eventInfo;
} EventFfi;

typedef struct EventArrayFfi {
    struct EventFfi data[MAX_EVENT_NUM_FFI];
    uint32_t len;
} EventArrayFfi;

typedef struct CommonOutputFfi {
    int32_t result;
    uint8_t hasFatalError;
    struct EventArrayFfi events;
} CommonOutputFfi;

typedef struct DeviceKeyFfi {
    int32_t deviceIdType;
    struct DataArray64Ffi deviceId;
    int32_t userId;
} DeviceKeyFfi;

typedef struct Int32Array64Ffi {
    int32_t data[MAX_DATA_LEN_64];
    uint32_t len;
} Int32Array64Ffi;

typedef struct PersistedCompanionStatusFfi {
    uint64_t templateId;
    int32_t hostUserId;
    struct DeviceKeyFfi companionDeviceKey;
    uint8_t isValid;
    struct Int32Array64Ffi enabledBusinessIds;
    uint64_t addedTime;
    uint16_t secureProtocolId;
    struct DataArray256Ffi deviceModel;
    struct DataArray256Ffi deviceUserName;
    struct DataArray256Ffi deviceName;
} PersistedCompanionStatusFfi;

typedef struct PersistedHostBindingStatusFfi {
    int32_t bindingId;
    int32_t companionUserId;
    struct DeviceKeyFfi hostDeviceKey;
    bool isTokenValid;
} PersistedHostBindingStatusFfi;

typedef struct CompanionStatusArrayFfi {
    struct PersistedCompanionStatusFfi data[MAX_TEMPLATE_ID_NUM_PER_USER_FFI];
    uint32_t len;
} CompanionStatusArrayFfi;

typedef struct HostBindingStatusArrayFfi {
    struct PersistedHostBindingStatusFfi data[MAX_TEMPLATE_ID_NUM_PER_USER_FFI];
    uint32_t len;
} HostBindingStatusArrayFfi;

typedef struct PlaceHolderFfi InitInputFfi;

typedef struct PlaceHolderFfi InitOutputFfi;

typedef struct PlaceHolderFfi GetExecutorInfoInputFfi;

typedef struct GetExecutorInfoOutputFfi {
    int32_t esl;
    int32_t maxTemplateAcl;
    struct DataArray1024Ffi publicKey;
} GetExecutorInfoOutputFfi;

typedef struct HostRegisterFinishInputFfi {
    struct TemplateIdArrayFfi templateIds;
    struct DataArray1024Ffi publicKey;
    struct DataArray1024Ffi fwkMsg;
} HostRegisterFinishInputFfi;

typedef struct PlaceHolderFfi HostRegisterFinishOutputFfi;

typedef struct HostGetPersistedStatusInputFfi {
    int32_t userId;
} HostGetPersistedStatusInputFfi;

typedef struct HostGetPersistedStatusOutputFfi {
    struct CompanionStatusArrayFfi companionStatusList;
} HostGetPersistedStatusOutputFfi;

typedef struct HostBeginCompanionCheckInputFfi {
    int32_t requestId;
} HostBeginCompanionCheckInputFfi;

typedef struct HostBeginCompanionCheckOutputFfi {
    uint64_t challenge;
    uint8_t salt[SALT_LEN_FFI];
} HostBeginCompanionCheckOutputFfi;

typedef struct Uint16Array64Ffi {
    uint16_t data[MAX_DATA_LEN_64];
    uint32_t len;
} Uint16Array64Ffi;

typedef struct HostEndCompanionCheckInputFfi {
    int32_t requestId;
    uint64_t templateId;
    struct Uint16Array64Ffi protocalList;
    struct Uint16Array64Ffi capabilityList;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostEndCompanionCheckInputFfi;

typedef struct PlaceHolderFfi HostEndCompanionCheckOutputFfi;

typedef struct HostCancelCompanionCheckInputFfi {
    int32_t requestId;
} HostCancelCompanionCheckInputFfi;

typedef struct PlaceHolderFfi HostCancelCompanionCheckOutputFfi;

typedef struct HostGetInitKeyNegotiationInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
} HostGetInitKeyNegotiationInputFfi;

typedef struct HostGetInitKeyNegotiationOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostGetInitKeyNegotiationOutputFfi;

typedef struct HostBeginAddCompanionInputFfi {
    int32_t requestId;
    uint64_t scheduleId;
    struct DeviceKeyFfi hostDeviceKey;
    struct DeviceKeyFfi companionDeviceKey;
    struct DataArray1024Ffi fwkMessage;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostBeginAddCompanionInputFfi;

typedef struct HostBeginAddCompanionOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostBeginAddCompanionOutputFfi;

typedef struct HostEndAddCompanionInputFfi {
    int32_t requestId;
    struct PersistedCompanionStatusFfi companionStatus;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostEndAddCompanionInputFfi;

typedef struct HostEndAddCompanionOutputFfi {
    struct DataArray1024Ffi fwkMessage;
    struct DataArray1024Ffi secMessage;
    uint64_t templateId;
    int32_t atl;
} HostEndAddCompanionOutputFfi;

typedef struct HostCancelAddCompanionInputFfi {
    int32_t requestId;
} HostCancelAddCompanionInputFfi;

typedef struct PlaceHolderFfi HostCancelAddCompanionOutputFfi;

typedef struct HostRemoveCompanionInputFfi {
    uint64_t templateId;
} HostRemoveCompanionInputFfi;

typedef struct HostRemoveCompanionOutputFfi {
    int32_t userId;
    struct DeviceKeyFfi companionDeviceKey;
} HostRemoveCompanionOutputFfi;

typedef struct HostPreIssueTokenInputFfi {
    int32_t requestId;
    uint64_t templateId;
    struct DataArray1024Ffi fwkMessage;
} HostPreIssueTokenInputFfi;

typedef struct HostPreIssueTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostPreIssueTokenOutputFfi;

typedef struct HostBeginIssueTokenInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostBeginIssueTokenInputFfi;

typedef struct HostBeginIssueTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostBeginIssueTokenOutputFfi;

typedef struct HostEndIssueTokenInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostEndIssueTokenInputFfi;

typedef struct HostEndIssueTokenOutputFfi {
    int32_t atl;
} HostEndIssueTokenOutputFfi;

typedef struct HostCancelIssueTokenInputFfi {
    int32_t requestId;
} HostCancelIssueTokenInputFfi;

typedef struct PlaceHolderFfi HostCancelIssueTokenOutputFfi;

typedef struct HostActivateTokenInputFfi {
    int32_t requestId;
} HostActivateTokenInputFfi;

typedef struct PlaceHolderFfi HostActivateTokenOutputFfi;

typedef struct HostBeginTokenAuthInputFfi {
    int32_t requestId;
    uint64_t scheduleId;
    uint64_t templateId;
    struct DataArray1024Ffi fwkMessage;
} HostBeginTokenAuthInputFfi;

typedef struct HostBeginTokenAuthOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostBeginTokenAuthOutputFfi;

typedef struct HostEndTokenAuthInputFfi {
    int32_t requestId;
    uint64_t templateId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostEndTokenAuthInputFfi;

typedef struct HostEndTokenAuthOutputFfi {
    struct DataArray1024Ffi fwkMessage;
} HostEndTokenAuthOutputFfi;

typedef struct HostRevokeTokenInputFfi {
    uint64_t templateId;
} HostRevokeTokenInputFfi;

typedef struct PlaceHolderFfi HostRevokeTokenOutputFfi;

typedef struct HostUpdateCompanionStatusInputFfi {
    uint64_t templateId;
    struct DataArray256Ffi deviceName;
    struct DataArray256Ffi deviceUserName;
} HostUpdateCompanionStatusInputFfi;

typedef struct PlaceHolderFfi HostUpdateCompanionStatusOutputFfi;

typedef struct HostUpdateCompanionEnabledBusinessIdsInputFfi {
    uint64_t templateId;
    struct Int32Array64Ffi businessIds;
} HostUpdateCompanionEnabledBusinessIdsInputFfi;

typedef struct PlaceHolderFfi HostUpdateCompanionEnabledBusinessIdsOutputFfi;

typedef struct HostCheckTemplateEnrolledInputFfi {
    uint64_t templateId;
} HostCheckTemplateEnrolledInputFfi;

typedef struct HostCheckTemplateEnrolledOutputFfi {
    uint8_t enrolled;
} HostCheckTemplateEnrolledOutputFfi;

typedef struct HostBeginDelegateAuthInputFfi {
    int32_t requestId;
    uint64_t scheduleId;
    uint64_t templateId;
    struct DataArray1024Ffi fwkMessage;
} HostBeginDelegateAuthInputFfi;

typedef struct HostBeginDelegateAuthOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostBeginDelegateAuthOutputFfi;

typedef struct HostEndDelegateAuthInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostEndDelegateAuthInputFfi;

typedef struct HostEndDelegateAuthOutputFfi {
    struct DataArray1024Ffi fwkMessage;
    int32_t authType;
    int32_t atl;
} HostEndDelegateAuthOutputFfi;

typedef struct HostCancelDelegateAuthInputFfi {
    int32_t requestId;
} HostCancelDelegateAuthInputFfi;

typedef struct PlaceHolderFfi HostCancelDelegateAuthOutputFfi;

typedef struct HostProcessPreObtainTokenInputFfi {
    int32_t requestId;
    uint64_t templateId;
    uint16_t secureProtocolId;
} HostProcessPreObtainTokenInputFfi;

typedef struct HostProcessPreObtainTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostProcessPreObtainTokenOutputFfi;

typedef struct HostProcessObtainTokenInputFfi {
    int32_t requestId;
    uint64_t templateId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostProcessObtainTokenInputFfi;

typedef struct HostProcessObtainTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
    int32_t atl;
} HostProcessObtainTokenOutputFfi;

typedef struct HostCancelObtainTokenInputFfi {
    int32_t requestId;
} HostCancelObtainTokenInputFfi;

typedef struct PlaceHolderFfi HostCancelObtainTokenOutputFfi;

typedef struct CompanionGetPersistedStatusInputFfi {
    int32_t userId;
} CompanionGetPersistedStatusInputFfi;

typedef struct CompanionGetPersistedStatusOutputFfi {
    struct HostBindingStatusArrayFfi bindingStatusList;
} CompanionGetPersistedStatusOutputFfi;

typedef struct CompanionProcessCheckInputFfi {
    int32_t bindingId;
    struct Uint16Array64Ffi capabilityList;
    uint16_t secureProtocolId;
    uint8_t salt[SALT_LEN_FFI];
    uint64_t challenge;
    struct DataArray1024Ffi secMessage;
} CompanionProcessCheckInputFfi;

typedef struct CompanionProcessCheckOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionProcessCheckOutputFfi;

typedef struct CompanionInitKeyNegotiationInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DeviceKeyFfi companionDeviceKey;
    struct DeviceKeyFfi hostDeviceKey;
    struct DataArray1024Ffi secMessage;
} CompanionInitKeyNegotiationInputFfi;

typedef struct CompanionInitKeyNegotiationOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionInitKeyNegotiationOutputFfi;

typedef struct CompanionBeginAddHostBindingInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionBeginAddHostBindingInputFfi;

typedef struct CompanionBeginAddHostBindingOutputFfi {
    struct DataArray1024Ffi secMessage;
    int32_t bindingId;
    struct PersistedHostBindingStatusFfi bindingStatus;
} CompanionBeginAddHostBindingOutputFfi;

typedef struct CompanionEndAddHostBindingInputFfi {
    int32_t requestId;
    int32_t result;
    struct DataArray1024Ffi secMessage;
} CompanionEndAddHostBindingInputFfi;

typedef struct CompanionEndAddHostBindingOutputFfi {
    int32_t bindingId;
} CompanionEndAddHostBindingOutputFfi;

typedef struct CompanionRemoveHostBindingInputFfi {
    int32_t bindingId;
} CompanionRemoveHostBindingInputFfi;

typedef struct PlaceHolderFfi CompanionRemoveHostBindingOutputFfi;

typedef struct CompanionPreIssueTokenInputFfi {
    int32_t requestId;
    int32_t bindingId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionPreIssueTokenInputFfi;

typedef struct CompanionPreIssueTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionPreIssueTokenOutputFfi;

typedef struct CompanionProcessIssueTokenInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionProcessIssueTokenInputFfi;

typedef struct CompanionProcessIssueTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionProcessIssueTokenOutputFfi;

typedef struct CompanionCancelIssueTokenInputFfi {
    int32_t requestId;
} CompanionCancelIssueTokenInputFfi;

typedef struct PlaceHolderFfi CompanionCancelIssueTokenOutputFfi;

typedef struct CompanionProcessTokenAuthInputFfi {
    int32_t bindingId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionProcessTokenAuthInputFfi;

typedef struct CompanionProcessTokenAuthOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionProcessTokenAuthOutputFfi;

typedef struct CompanionRevokeTokenInputFfi {
    int32_t bindingId;
} CompanionRevokeTokenInputFfi;

typedef struct PlaceHolderFfi CompanionRevokeTokenOutputFfi;

typedef struct CompanionBeginDelegateAuthInputFfi {
    int32_t requestId;
    int32_t bindingId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionBeginDelegateAuthInputFfi;

typedef struct CompanionBeginDelegateAuthOutputFfi {
    uint64_t challenge;
    int32_t atl;
} CompanionBeginDelegateAuthOutputFfi;

typedef struct CompanionEndDelegateAuthInputFfi {
    int32_t requestId;
    int32_t result;
    uint8_t authToken[AUTH_TOKEN_SIZE_FFI];
} CompanionEndDelegateAuthInputFfi;

typedef struct CompanionEndDelegateAuthOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionEndDelegateAuthOutputFfi;

typedef struct CompanionBeginObtainTokenInputFfi {
    int32_t requestId;
    int32_t bindingId;
    struct DataArray1024Ffi fwkMessage;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionBeginObtainTokenInputFfi;

typedef struct CompanionBeginObtainTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionBeginObtainTokenOutputFfi;

typedef struct CompanionEndObtainTokenInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionEndObtainTokenInputFfi;

typedef struct PlaceHolderFfi CompanionEndObtainTokenOutputFfi;

typedef struct CompanionCancelObtainTokenInputFfi {
    int32_t requestId;
} CompanionCancelObtainTokenInputFfi;

typedef struct PlaceHolderFfi CompanionCancelObtainTokenOutputFfi;

int32_t init_rust_env(void);

int32_t uninit_rust_env(void);

int32_t invoke_rust_command(struct RustCommandParam Param);

#ifdef __cplusplus
}
#endif

#endif /* COMPANION_DEVICE_AUTH_FFI_H */
