/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import CompanionDeviceAuthTypes;
import IIpcAvailableDeviceStatusCallback;
import IIpcTemplateStatusCallback;
import IIpcContinuousAuthStatusCallback;
import IIpcDeviceSelectCallback;

option_stub_hooks on;

interface OHOS.UserIam.CompanionDeviceAuth.ICompanionDeviceAuth {
    void SubscribeAvailableDeviceStatus([in] int localUserId,
        [in] IIpcAvailableDeviceStatusCallback deviceStatusCallback, [out] int resultCode);

    void UnsubscribeAvailableDeviceStatus([in] IIpcAvailableDeviceStatusCallback deviceStatusCallback,
        [out] int resultCode);

    void SubscribeTemplateStatusChange([in] int localUserId,
        [in] IIpcTemplateStatusCallback templateStatusCallback, [out] int resultCode);

    void UnsubscribeTemplateStatusChange([in] IIpcTemplateStatusCallback templateStatusCallback,
        [out] int resultCode);

    void SubscribeContinuousAuthStatusChange([in] IpcSubscribeContinuousAuthStatusParam param,
        [in] IIpcContinuousAuthStatusCallback continuousAuthStatusCallback, [out] int resultCode);

    void UnsubscribeContinuousAuthStatusChange([in] IIpcContinuousAuthStatusCallback continuousAuthStatusCallback,
        [out] int resultCode);

    void GetTemplateStatus([in] int localUserId,
        [out] IpcTemplateStatus[] templateStatusList, [out] int resultCode);

    void RegisterDeviceSelectCallback([in] IIpcDeviceSelectCallback deviceSelectCallback,
        [out] int resultCode);

    void UnregisterDeviceSelectCallback([out] int resultCode);

    void UpdateTemplateEnabledBusinessIds([in] unsigned long templateId,
        [in] int[] enabledBusinessIds, [out] int resultCode);
    
    void CheckLocalUserIdValid([in] int localUserId, [out] boolean isUserIdValid, [out] int resultCode);
}
