/*
 * Copyright (C) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Auto-generated C bindings for user_auth_rs
 * Generated by cbindgen from Rust FFI definitions
 */

#ifndef COMPANION_DEVICE_AUTH_FFI_H
#define COMPANION_DEVICE_AUTH_FFI_H

#include "companion_device_auth_ffi_types.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct PlaceHolderFfi InitInputFfi;

typedef struct PlaceHolderFfi InitOutputFfi;

typedef struct PlaceHolderFfi GetExecutorInfoInputFfi;

typedef struct GetExecutorInfoOutputFfi {
    int32_t esl;
    int32_t maxTemplateAcl;
    struct DataArray1024Ffi publicKey;
} GetExecutorInfoOutputFfi;

typedef struct HostRegisterFinishInputFfi {
    struct TemplateIdArrayFfi templateIds;
    struct DataArray1024Ffi publicKey;
    struct DataArray1024Ffi fwkMsg;
} HostRegisterFinishInputFfi;

typedef struct PlaceHolderFfi HostRegisterFinishOutputFfi;

typedef struct HostGetPersistedStatusInputFfi {
    int32_t userId;
} HostGetPersistedStatusInputFfi;

typedef struct HostGetPersistedStatusOutputFfi {
    struct CompanionStatusArrayFfi companionStatusList;
} HostGetPersistedStatusOutputFfi;

typedef struct SetActiveUserInputFfi {
    int32_t userId;
} SetActiveUserInputFfi;

typedef struct PlaceHolderFfi SetActiveUserOutputFfi;

typedef struct HostBeginCompanionCheckInputFfi {
    int32_t requestId;
} HostBeginCompanionCheckInputFfi;

typedef struct HostBeginCompanionCheckOutputFfi {
    uint64_t challenge;
    struct DataArray32Ffi salt;
} HostBeginCompanionCheckOutputFfi;

typedef struct HostEndCompanionCheckInputFfi {
    int32_t requestId;
    uint64_t templateId;
    struct Uint16Array64Ffi protocolList;
    struct Uint16Array64Ffi capabilityList;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostEndCompanionCheckInputFfi;

typedef struct PlaceHolderFfi HostEndCompanionCheckOutputFfi;

typedef struct HostCancelCompanionCheckInputFfi {
    int32_t requestId;
} HostCancelCompanionCheckInputFfi;

typedef struct PlaceHolderFfi HostCancelCompanionCheckOutputFfi;

typedef struct HostGetInitKeyNegotiationInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
} HostGetInitKeyNegotiationInputFfi;

typedef struct HostGetInitKeyNegotiationOutputFfi {
    struct DataArray20000Ffi secMessage;
} HostGetInitKeyNegotiationOutputFfi;

typedef struct HostBeginAddCompanionInputFfi {
    int32_t requestId;
    uint64_t scheduleId;
    struct DeviceKeyFfi hostDeviceKey;
    struct DeviceKeyFfi companionDeviceKey;
    struct DataArray1024Ffi fwkMessage;
    uint16_t secureProtocolId;
    struct DataArray20000Ffi secMessage;
} HostBeginAddCompanionInputFfi;

typedef struct HostBeginAddCompanionOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostBeginAddCompanionOutputFfi;

typedef struct HostEndAddCompanionInputFfi {
    int32_t requestId;
    struct PersistedCompanionStatusFfi companionStatus;
    uint16_t secureProtocolId;
    struct Uint16Array64Ffi protocolList;
    struct Uint16Array64Ffi capabilityList;
    struct DataArray1024Ffi secMessage;
} HostEndAddCompanionInputFfi;

typedef struct HostEndAddCompanionOutputFfi {
    struct DataArray1024Ffi fwkMessage;
    struct DataArray1024Ffi secMessage;
    uint64_t templateId;
    int32_t atl;
    uint64_t addedTime;
} HostEndAddCompanionOutputFfi;

typedef struct HostCancelAddCompanionInputFfi {
    int32_t requestId;
} HostCancelAddCompanionInputFfi;

typedef struct PlaceHolderFfi HostCancelAddCompanionOutputFfi;

typedef struct HostRemoveCompanionInputFfi {
    uint64_t templateId;
} HostRemoveCompanionInputFfi;

typedef struct HostRemoveCompanionOutputFfi {
    int32_t userId;
    struct DeviceKeyFfi companionDeviceKey;
} HostRemoveCompanionOutputFfi;

typedef struct HostPreIssueTokenInputFfi {
    int32_t requestId;
    uint64_t templateId;
    struct DataArray1024Ffi fwkMessage;
} HostPreIssueTokenInputFfi;

typedef struct HostPreIssueTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostPreIssueTokenOutputFfi;

typedef struct HostBeginIssueTokenInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostBeginIssueTokenInputFfi;

typedef struct HostBeginIssueTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostBeginIssueTokenOutputFfi;

typedef struct HostEndIssueTokenInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostEndIssueTokenInputFfi;

typedef struct HostEndIssueTokenOutputFfi {
    int32_t atl;
} HostEndIssueTokenOutputFfi;

typedef struct HostCancelIssueTokenInputFfi {
    int32_t requestId;
} HostCancelIssueTokenInputFfi;

typedef struct PlaceHolderFfi HostCancelIssueTokenOutputFfi;

typedef struct HostBeginTokenAuthInputFfi {
    int32_t requestId;
    uint64_t scheduleId;
    uint64_t templateId;
    struct DataArray1024Ffi fwkMessage;
} HostBeginTokenAuthInputFfi;

typedef struct HostBeginTokenAuthOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostBeginTokenAuthOutputFfi;

typedef struct HostEndTokenAuthInputFfi {
    int32_t requestId;
    uint64_t templateId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostEndTokenAuthInputFfi;

typedef struct HostEndTokenAuthOutputFfi {
    struct DataArray1024Ffi fwkMessage;
} HostEndTokenAuthOutputFfi;

typedef struct HostRevokeTokenInputFfi {
    uint64_t templateId;
} HostRevokeTokenInputFfi;

typedef struct PlaceHolderFfi HostRevokeTokenOutputFfi;

typedef struct HostUpdateCompanionStatusInputFfi {
    uint64_t templateId;
    struct DataArray256Ffi deviceName;
    struct DataArray256Ffi deviceUserName;
} HostUpdateCompanionStatusInputFfi;

typedef struct PlaceHolderFfi HostUpdateCompanionStatusOutputFfi;

typedef struct HostUpdateCompanionEnabledBusinessIdsInputFfi {
    uint64_t templateId;
    struct Int32Array64Ffi businessIds;
} HostUpdateCompanionEnabledBusinessIdsInputFfi;

typedef struct PlaceHolderFfi HostUpdateCompanionEnabledBusinessIdsOutputFfi;

typedef struct HostCheckTemplateEnrolledInputFfi {
    uint64_t templateId;
} HostCheckTemplateEnrolledInputFfi;

typedef struct HostCheckTemplateEnrolledOutputFfi {
    uint8_t enrolled;
} HostCheckTemplateEnrolledOutputFfi;

typedef struct HostBeginDelegateAuthInputFfi {
    int32_t requestId;
    uint64_t scheduleId;
    uint64_t templateId;
    struct DataArray1024Ffi fwkMessage;
} HostBeginDelegateAuthInputFfi;

typedef struct HostBeginDelegateAuthOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostBeginDelegateAuthOutputFfi;

typedef struct HostEndDelegateAuthInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostEndDelegateAuthInputFfi;

typedef struct HostEndDelegateAuthOutputFfi {
    struct DataArray1024Ffi fwkMessage;
    int32_t authType;
    int32_t atl;
} HostEndDelegateAuthOutputFfi;

typedef struct HostCancelDelegateAuthInputFfi {
    int32_t requestId;
} HostCancelDelegateAuthInputFfi;

typedef struct PlaceHolderFfi HostCancelDelegateAuthOutputFfi;

typedef struct HostProcessPreObtainTokenInputFfi {
    int32_t requestId;
    uint64_t templateId;
    uint16_t secureProtocolId;
} HostProcessPreObtainTokenInputFfi;

typedef struct HostProcessPreObtainTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} HostProcessPreObtainTokenOutputFfi;

typedef struct HostProcessObtainTokenInputFfi {
    int32_t requestId;
    uint64_t templateId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} HostProcessObtainTokenInputFfi;

typedef struct HostProcessObtainTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
    int32_t atl;
} HostProcessObtainTokenOutputFfi;

typedef struct HostCancelObtainTokenInputFfi {
    int32_t requestId;
} HostCancelObtainTokenInputFfi;

typedef struct PlaceHolderFfi HostCancelObtainTokenOutputFfi;

typedef struct HostUpdateTokenInputFfi {
    uint64_t templateId;
    struct DataArray1024Ffi fwkMessage;
} HostUpdateTokenInputFfi;

typedef struct HostUpdateTokenOutputFfi {
    bool needRedistribute;
} HostUpdateTokenOutputFfi;

typedef struct CompanionGetPersistedStatusInputFfi {
    int32_t userId;
} CompanionGetPersistedStatusInputFfi;

typedef struct CompanionGetPersistedStatusOutputFfi {
    struct HostBindingStatusArrayFfi bindingStatusList;
} CompanionGetPersistedStatusOutputFfi;

typedef struct CompanionProcessCheckInputFfi {
    int32_t bindingId;
    struct Uint16Array64Ffi capabilityList;
    uint16_t secureProtocolId;
    struct DataArray32Ffi salt;
    uint64_t challenge;
    struct DataArray1024Ffi secMessage;
} CompanionProcessCheckInputFfi;

typedef struct CompanionProcessCheckOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionProcessCheckOutputFfi;

typedef struct CompanionInitKeyNegotiationInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DeviceKeyFfi companionDeviceKey;
    struct DeviceKeyFfi hostDeviceKey;
    struct DataArray20000Ffi secMessage;
} CompanionInitKeyNegotiationInputFfi;

typedef struct CompanionInitKeyNegotiationOutputFfi {
    struct DataArray20000Ffi secMessage;
} CompanionInitKeyNegotiationOutputFfi;

typedef struct CompanionBeginAddHostBindingInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionBeginAddHostBindingInputFfi;

typedef struct CompanionBeginAddHostBindingOutputFfi {
    struct DataArray1024Ffi secMessage;
    int32_t bindingId;
    struct PersistedHostBindingStatusFfi bindingStatus;
} CompanionBeginAddHostBindingOutputFfi;

typedef struct CompanionEndAddHostBindingInputFfi {
    int32_t requestId;
    int32_t result;
    struct DataArray1024Ffi secMessage;
} CompanionEndAddHostBindingInputFfi;

typedef struct CompanionEndAddHostBindingOutputFfi {
    int32_t bindingId;
} CompanionEndAddHostBindingOutputFfi;

typedef struct CompanionRemoveHostBindingInputFfi {
    int32_t bindingId;
} CompanionRemoveHostBindingInputFfi;

typedef struct PlaceHolderFfi CompanionRemoveHostBindingOutputFfi;

typedef struct CompanionPreIssueTokenInputFfi {
    int32_t requestId;
    int32_t bindingId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionPreIssueTokenInputFfi;

typedef struct CompanionPreIssueTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionPreIssueTokenOutputFfi;

typedef struct CompanionProcessIssueTokenInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionProcessIssueTokenInputFfi;

typedef struct CompanionProcessIssueTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionProcessIssueTokenOutputFfi;

typedef struct CompanionCancelIssueTokenInputFfi {
    int32_t requestId;
} CompanionCancelIssueTokenInputFfi;

typedef struct PlaceHolderFfi CompanionCancelIssueTokenOutputFfi;

typedef struct CompanionProcessTokenAuthInputFfi {
    int32_t bindingId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionProcessTokenAuthInputFfi;

typedef struct CompanionProcessTokenAuthOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionProcessTokenAuthOutputFfi;

typedef struct CompanionRevokeTokenInputFfi {
    int32_t bindingId;
} CompanionRevokeTokenInputFfi;

typedef struct PlaceHolderFfi CompanionRevokeTokenOutputFfi;

typedef struct CompanionBeginDelegateAuthInputFfi {
    int32_t requestId;
    int32_t bindingId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionBeginDelegateAuthInputFfi;

typedef struct CompanionBeginDelegateAuthOutputFfi {
    uint64_t challenge;
    int32_t atl;
} CompanionBeginDelegateAuthOutputFfi;

typedef struct CompanionEndDelegateAuthInputFfi {
    int32_t requestId;
    int32_t result;
    struct DataArray1024Ffi authToken;
} CompanionEndDelegateAuthInputFfi;

typedef struct CompanionEndDelegateAuthOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionEndDelegateAuthOutputFfi;

typedef struct CompanionBeginObtainTokenInputFfi {
    int32_t requestId;
    int32_t bindingId;
    struct DataArray1024Ffi fwkMessage;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionBeginObtainTokenInputFfi;

typedef struct CompanionBeginObtainTokenOutputFfi {
    struct DataArray1024Ffi secMessage;
} CompanionBeginObtainTokenOutputFfi;

typedef struct CompanionEndObtainTokenInputFfi {
    int32_t requestId;
    uint16_t secureProtocolId;
    struct DataArray1024Ffi secMessage;
} CompanionEndObtainTokenInputFfi;

typedef struct PlaceHolderFfi CompanionEndObtainTokenOutputFfi;

typedef struct CompanionCancelObtainTokenInputFfi {
    int32_t requestId;
} CompanionCancelObtainTokenInputFfi;

typedef struct PlaceHolderFfi CompanionCancelObtainTokenOutputFfi;

int32_t init_rust_env(void);

int32_t uninit_rust_env(void);

int32_t invoke_rust_command(struct RustCommandParam param);

#ifdef __cplusplus
}
#endif

#endif /* COMPANION_DEVICE_AUTH_FFI_H */
